# SPDX-FileCopyrightText: 2025 Jesse Aubin <jesseb34r@jesseaubin.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[package]
name = "lotuslab-services"
edition = { workspace = true }

[dependencies]
lotuslab-types = { workspace = true }
lotuslab-db = { workspace = true }
