version = 1

[[annotations]]
path = "crates/lotuslab-core/icons/*"
precedence = "override"
SPDX-FileCopyrightText = "2025 Jesse Aubin <jesseb34r@jesseaubin.me"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "crates/lotuslab-core/**/*.json"
precedence = "override"
SPDX-FileCopyrightText = "2025 Jesse Aubin <jesseb34r@jesseaubin.me>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "frontend/package.json"
precedence = "override"
SPDX-FileCopyrightText = "2025 Jesse Aubin <jesseb34r@jesseaubin.me>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "Cargo.lock"
precedence = "override"
SPDX-FileCopyrightText = "2025 Jesse Aubin <jesseb34r@jesseaubin.me>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "frontend/bun.lock"
precedence = "override"
SPDX-FileCopyrightText = "2025 Jesse Aubin <jesseb34r@jesseaubin.me>"
SPDX-License-Identifier = "CC0-1.0"
