# SPDX-FileCopyrightText: 2025 Jesse Aubin <jesseb34r@jesseaubin.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Use faster linkers on Linux and Windows systems
# MacOS already has a fast linker.
[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=y"]

[profile.dev]
debug = 1 # set to `true` if you want to use a debugger

[profile.release]
opt-level = "s"
strip = true
lto = true
codegen-units = 1
